### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by madmenvacationrentals** [brainstormforce/header-footer-elementor#505]
### Describe the bug:

None of the pages on my website are working and shows this error:
Fatal error: Uncaught Error: Class 'Elementor\Scheme_Color' not found in /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/navmenu-addon-for-elementor/modules/menus/widgets/default-navmenu.php:199 Stack trace: #0 /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): ElementorMenus\Modules\Menus\Widgets\Default_Navmenu->_register_controls() #1 /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls() #2 /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #3 /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack() #4 /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/elementor/includes/bas in /home/customer/www/madmenvacationrentals.com/public_html/wp-content/plugins/navmenu-addon-for-elementor/modules/menus/widgets/default-navmenu.php on line 199

I uninstalled all plugins and determined it was this "Elementor Header & Footer Builder" as the one causing this error. I do need this plugin however for my website to look intact. How do I go about
getting this plugin to work for me and not bring this error? My website 
is [www.madmenvacationrentals.com](http://www.madmenvacationrentals.com/). Thank you for your help!

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by swapnilde** [comment]
Hello @madmenvacationrentals 

Thank you for contacting us.

We have fully deprecated use of `Scheme_Color` in our plugin `Elementor Header & Footer Builder` since  v1.5.9. We are not using this in our codebase anywhere anymore and replaced it with its successor Global_Colors and Global_Typography.

By looking at the error log above I am suspicious If this is `Elementor Header & Footer Builder` plugin.
We dont have a file called `default-navmenu.php` and a location like this `navmenu-addon-for-elementor/modules/menus/widgets/default-navmenu.php`. The plugin name seems this `navmenu-addon-for-elementor` and not `Elementor Header & Footer Builder`.

I would request you to recheck if you are using our plugin `Elementor Header & Footer Builder` by Brainstorm Force.
If that is the case you can open a official support ticket to us from here: https://uaelementor.com/support/open-a-ticket/

**Comment by madmenvacationrentals** [comment]
This is what it says in the plugin description:


Elementor Header & Footer BuilderActivate \| Delete | This powerful plugin allows creating a custom header, footer with Elementor and display them on selected locations. You can also create custom Elementor blocks and place them anywhere on the website with a shortcode.Version 1.6.9 \| By Brainstorm Force, Nikhil Chavan \| View details
-- | --


Elementor Header & Footer Builder
[Activate](https://madmenvacationrentals.com/wp-admin/plugins.php?action=activate&plugin=header-footer-elementor%2Fheader-footer-elementor.php&plugin_status=inactive&paged=1&s&_wpnonce=d3f8c36983) | [Delete](https://madmenvacationrentals.com/wp-admin/plugins.php?action=delete-selected&checked%5B0%5D=header-footer-elementor%2Fheader-footer-elementor.php&plugin_status=inactive&paged=1&s&_wpnonce=4d0680b76a)
This powerful plugin allows creating a custom header, footer with Elementor and display them on selected locations. You can also create custom Elementor blocks and place them anywhere on the website with a shortcode.

Version 1.6.9 | By [Brainstorm Force, Nikhil Chavan](https://www.brainstormforce.com/) | [View details](https://madmenvacationrentals.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=header-footer-elementor&TB_iframe=true&width=600&height=550)

Im am completely at a loss right now. My website is completely unusable and I dont know how to fix it. Ive been working on this for 3 days straight and cant loose any more time trying to figure this all out. I cant keep opening tickets. Can you please please pretty please help me? Can we schedule a meeting and I can share my screen or something so you can help me get this figured out today? It should not take long with someone like you that knows what they are doing. Thank you!

Best Regards, Rebecca

**Comment by sushmak02** [comment]
Hello @madmenvacationrentals,

Sorry for the trouble you are facing.

Temporarily please switch back to Elementor's older version to make your website usable.

Regarding the issue you are facing, we could not reproduce this at our end. Will you please provide the system status file from Elementor settings?
Refer - https://share.getcloudapp.com/E0ugrnXD

We need a few more details to track this further.

**Comment by Xylot01** [comment]
Hello @sushmak02,
i have the same problem.

The plugin ran great until Elementor was updated to version 3.6.x.
Since Elementor 3.6.0 and 3.6.1 my website shows a fatal error when the plugin is activated.
At the moment I rolled back to Elementor version 3.5.6 

WP version 5.9.2

Theme OceanWP  
Version: 3.1.4

Cheers

**Comment by sushmak02** [comment]
We have released the latest version 1.6.10 with the Elementor's latest version compatibility. Please update to the latest version.

**Comment by Xylot01** [comment]
Hello @sushmak02 
I have updated to version 1.6.10.
The problem is fixed now. :-)
Thanks for the support

**Comment by sushmak02** [comment]
Thank you @Xylot01 for verifying!

**Comment by madmenvacationrentals** [comment]
How to I keep it from automatically updating to the newer version? That happened today and had to go in and manually put back to older version...

**Comment by madmenvacationrentals** [comment]
> Hello @madmenvacationrentals,
> 
> Sorry for the trouble you are facing.
> 
> Temporarily please switch back to Elementor's older version to make your website usable.
> 
> Regarding the issue you are facing, we could not reproduce this at our end. Will you please provide the system status file from Elementor settings? Refer - https://share.getcloudapp.com/E0ugrnXD
> 
> We need a few more details to track this further.

It keeps automatically updating to the new version almost every day. How do I stop this from happeneing?????

**Comment by madmenvacationrentals** [comment]
@sushmak02 [sushmak02](https://github.com/sushmak02)

Yes it does seem the error is now coming from Navmenu Addon for Elementor. The header footer builder seems to now be working. How do I get in touch with Navmenu Addon for Elementor to tell them to update...
